[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 100
low-at = 20

format-full = %{T18}%{T-} <label-full>
label-full-font = 14
format-full-background = ${colors.yellow}
format-full-foreground = ${colors.black}
format-full-underline = ${colors.bg}
format-full-overline = ${colors.bg}
format-full-padding = 1

label-charging-font = 14
format-charging = H  <label-charging>
format-charging-font = 10
format-charging-background = ${colors.green}
format-charging-foreground = ${colors.black}
format-charging-padding = 1

label-discharging-font = 14
label-discharging-foreground = ${colors.cream}
format-discharging = %{T18}%{T-} <label-discharging>  
format-discharging-background = ${colors.bg-alt}
format-discharging-foreground = ${colors.green}
format-discharging-padding = 1

label-low-font = 14
format-low = %{T18}%{T-} <label-low>  
format-low-background = ${colors.red}
format-low-foreground = ${colors.black}
format-low-padding = 1
