[module/date]

type = internal/date
interval = 1 

date = %a, %d %b
label = %date%
label-font = 16 
label-foreground = ${colors.new}

format = %{A1:dunstify "Hello World" "This is a Test Notification":} %{A} <label>
format-foreground = ${colors.light-purple}
format-background = ${colors.bg-alt}
format-padding = 1

[module/time]
type = internal/date
interval = 1 

time = %I : %M : %S %p
label = %time%
label-font = 16
label-foreground = ${colors.new}

format =   <label> 
format-foreground = ${colors.light-purple}
format-background = ${colors.bg-alt}
format-padding = 1

