[module/date]

type = internal/date
interval = 1 

date = %A, %d %b
label = %date%
label-font = 20
label-foreground = ${colors.date}

format = %{A1:google-calendar-nativefier &:} %{A}<label>
format-foreground = ${colors.light-purple}
format-padding = 1

[module/time]
type = internal/date
interval = 1 

time = %I : %M : %S %p
label = %time%
label-font = 20 
label-foreground = ${colors.date}

format = <label> 
format-foreground = ${colors.light-purple}
format-padding = 1

