[module/i3-workspace]
type = internal/i3
format = <label-mode> <label-state>
index-sort = true

ws-icon-0 = 1;1
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;%{T8}%{T-}
ws-icon-9= 10;%{T8}%{T-} 

; Only show workspaces on the same output as the bar
pin-workspaces = true

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%

label-mode-padding = 1
label-mode-foreground = ${colors.bg-alt}
label-mode-background = ${colors.rose-pink}

;focused = Active workspace on focused monitor
label-focused = %icon%
label-focused-foreground = ${colors.bg}
label-focused-underline = ${colors.bg}
label-focused-overline = ${colors.bg}
label-focused-background = ${colors.rose-pink}
label-focused-font = 7
label-focused-padding = 1

;unfocused = Inactive workspace on any monitor
label-unfocused = %icon%
label-unfocused-foreground = ${colors.brownish-cream}
label-unfocused-font = 5
label-unfocused-padding = 1

;urgent = Workspace with urgency hint set
label-urgent = %icon%
label-urgent-background = ${colors.dark-red}
label-urgent-foreground = ${colors.black}
label-urgent-underline = ${colors.bg}
label-urgent-overline = ${colors.bg}
label-urgent-font = 7
label-urgent-padding = 1

label-separator = |
