[module/i3-workspace]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true

; Only show workspaces on the same output as the bar
pin-workspaces = true

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%

label-mode-padding = 1
label-mode-foreground = ${colors.bg-alt}
label-mode-background = ${colors.rose-pink}

; focused = Active workspace on focused monitor
label-focused = %name%
label-focused-font = 7
label-focused-foreground = ${colors.rose-pink}
label-focused-padding = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 1

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.red}
label-urgent-foreground = ${colors.black}
label-urgent-font = 7
label-urgent-padding = 1

label-separator = |
