[module/i3-workspace]
type = internal/i3
format = <label-mode> <label-state>
index-sort = true

; Only show workspaces on the same output as the bar
pin-workspaces = true

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%

label-mode-padding = 1
label-mode-foreground = ${colors.bg-alt}
label-mode-background = ${colors.rose-pink}

;focused = Active workspace on focused monitor
label-focused = %name%
label-focused-foreground = ${colors.bg}
label-focused-underline = ${colors.bg}
label-focused-overline = ${colors.bg}
label-focused-background = ${colors.rose-pink}
label-focused-font = 7
label-focused-padding = 1

;unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-foreground = ${colors.brownish-cream}
label-unfocused-font = 5
label-unfocused-padding = 1

;urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.dark-red}
label-urgent-foreground = ${colors.black}
label-urgent-underline = ${colors.bg}
label-urgent-overline = ${colors.bg}
label-urgent-font = 7
label-urgent-padding = 1

label-separator = |
