[module/restock]
type = custom/script
interval = 600
exec = ~/.scripts/stock.sh
click-left = google-chrome-stable 'https://www.keychron.com/products/keychron-q1-qmk-custom-mechanical-keyboard-knob-version?variant=39610589970521' &

label = %output%
label-font = 15
label-foreground = ${colors.brownish-cream}
format =  <label>
;format-background = ${colors.bg-alt}
format-foreground = ${colors.green}
format-padding = 1
format-font = 3

;label-fail = %output%
;label-fail-font = 15
;label-fail-foreground = ${colors.black}
;format-fail =  <label-fail>
;format-fail-background = ${colors.bg-alt}
;format-fail-foreground = ${colors.dark-red}
;format-fail-padding = 1
;format-fail-font = 3


