[module/temperature]
type = internal/temperature
interval = 0.5
thermal-zone = 0
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp2_input
warn-temperature = 70 

label = %temperature-c%
label-font = 14
format =  <label>
format-font = 7
format-background = ${colors.bg}
format-foreground = ${colors.brownish-cream}
format-padding = 1
format-underline = ${colors.bg}
format-overline = ${colors.bg}

format-warn =  <label-warn>
label-warn-font = 14
format-warn-font = 7
format-warn-foreground = ${colors.dark-red}
format-warn-background = ${colors.bg}
format-warn-underline = ${colors.bg}
format-warn-overline = ${colors.bg}
format-warn-padding = 1
 
[module/memory]
type = internal/memory
interval = 1
label =  %gb_used%
label-font = 14
format =  <label>
format-font = 7
format-background = ${colors.bg}
format-foreground = ${colors.brownish-cream}
format-underline = ${colors.bg}
format-overline = ${colors.bg}
format-padding = 1

[module/cpu]
type = internal/cpu
interval = 0.5
label = %percentage%%
label-font = 14
format =  <label>
format-font = 7
format-background = ${colors.bg}
format-foreground = ${colors.brownish-cream}
format-padding = 1
format-underline = ${colors.bg}
format-overline = ${colors.bg}

[module/separator-pink]
type = custom/text
content = "|"
content-background = ${colors.bg}
content-foreground = ${colors.black}
content-font = 7
content-overline = ${colors.bg}
content-underline = ${colors.bg}
