[module/polypomo]
type = custom/script

exec = ~/.config/polybar/Modules/polypomo/polypomo
tail = true

label = %output%
format-foreground = ${colors.new}
label-font = 21 
click-left = ~/.config/polybar/Modules/polypomo/polypomo toggle
click-right = ~/.config/polybar/Modules/polypomo/polypomo end
click-middle = ~/.config/polybar/Modules/polypomo/polypomo lock
scroll-up = ~/.config/polybar/Modules/polypomo/polypomo time +60
scroll-down = ~/.config/polybar/Modules/polypomo/polypomo time -60

