[module/separator]
type = custom/text
content = "|"
content-background = ${colors.bg-alt}
content-foreground = ${colors.black}
content-font = 7

[module/blank_space]
type = custom/text
content = " "

[module/separator-pink]
type = custom/text
content = "|"
content-background = ${colors.rose-pink}
content-foreground = ${colors.black}
content-font = 7
content-overline = ${colors.bg}
content-underline = ${colors.bg}
