[module/pulseaudio]
type = internal/pulseaudio
interval = 5

format-volume = 墳 <label-volume> 
format-volume-background = ${colors.bg-alt}
format-volume-foreground = ${colors.green}
format-volume-padding = 1
format-volume-font = 7

label-volume = %percentage%% 
label-volume-foreground = ${colors.brownish-cream}
label-volume-font = 15

format-muted = 婢 <label-muted> 
format-muted-background = ${colors.bg-alt}
format-muted-foreground = ${colors.dark-red}
format-muted-padding = 1
format-muted-font = 7

label-muted = Muted   
label-muted-font = 15
label-muted-foreground = ${colors.black}

